### ISSUE TITLE
Build failure with recent SDK updates (17 Feb 2020)

### ISSUE THREAD

**Issue by ihnorton** [conda-forge/aws-sdk-cpp-feedstock#115]
I took a quick look at the current (17Feb2020) build failures, and they seem to be caused by a mismatch between the SDK default to build as a shared lib and the AWS-core build defaults. Ref: https://github.com/aws/aws-sdk-cpp/issues/1309

```
CMake Error at /home/conda/feedstock_root/build_artifacts/aws-sdk-cpp_1581964763500/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake:8 (include):
  include could not find load file:

    /home/conda/feedstock_root/build_artifacts/aws-sdk-cpp_1581964763500/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/aws-c-event-stream/cmake/static/aws-c-event-stream-targets.cmake
Call Stack (most recent call first):
  /home/conda/feedstock_root/build_artifacts/aws-sdk-cpp_1581964763500/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/conda/feedstock_root/build_artifacts/aws-sdk-cpp_1581964763500/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:2 (find_dependency)
  /home/conda/feedstock_root/build_artifacts/aws-sdk-cpp_1581964763500/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/AWSSDK/AWSSDKConfig.cmake:303 (find_package)
  CMakeLists.txt:7 (find_package)
```

**Comment by dblock** [comment]
Workaround is to add `option(BUILD_SHARED_LIBS "Build shared libraries" ON)`

**Comment by ihnorton** [comment]
@dblock thanks for the suggestion -- I've tried that a few times, both with and w/out unity build enabled, but unfortunately it did not help. Maybe I missed something, but I haven't had more time to debug recently so I opened this issue as a reminder when I do.

- [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=127987&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c)
  - [corresponding commit](https://github.com/conda-forge/aws-sdk-cpp-feedstock/commit/287bf659449d51633adefda5e0f48d22f2576281)
- [previous run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=122277&view=results) w/ UNITY_BUILD=ON and BUILD_SHARED_LIBS=ON
  - [corresponding commit](https://github.com/conda-forge/aws-sdk-cpp-feedstock/commit/f3f8c8718c25e380aa625f0bf3d3516ff1d6956e)
