### ISSUE TITLE
BUILD_ONLY

### ISSUE THREAD

**Issue by hobu** [conda-forge/aws-sdk-cpp-feedstock#169]
What makes a SDK member get added to the BUILD_ONLY configuration? Is there a reason to not build everything? For example, I would very much like to add SNS and SQS. I'm happy to make a PR doing so, but I'm wondering what is causing that to be limited in the first place.

**Comment by xhochy** [comment]
The most probable cause is package size / need. Other components were not needed before. I'll merge the PR and in future we should try to make this a multiple output package that builds everything at once but provides each component as a single output to have a more efficient installation size.
